### ISSUE TITLE
4.1.2 Species Search: The search results should be listed alphabetically by scientific name or common name, whichever is selected.

### ISSUE THREAD

**Issue by jdrever** [jdrever/ShropBotSoc#21]
See https://github.com/jdrever/ShropBotSoc/blob/develop/docs/specification.md#412-species-search

**Comment by charlesroper** [comment]
Do they also want taxonomic sort order sorting? This is often the preferred sort order among expert users. I am not sure if the NBN API can do taxon sort order (which is surprising). I had a look at the API docs, but couldn't see anything. Worth asking them.

**Comment by jdrever** [comment]
Can't see how to sort by common name.  Seems to sort by scientific name by default.  I'm getting a bit confused by the distinction between sorting by scientific name and sorting and taxonomic sorting - can you explain the difference @charlesroper ?

**Comment by charlesroper** [comment]
So, taxonomic order (also known as [taxonomic sequence](https://en.m.wikipedia.org/wiki/Taxonomic_sequence) and sometimes "systematic" ordering). It's a good question and one that's fundamental to the user experience of presenting taxonomic data. It's a bit complicated to explain, so bear with me. 

**Short answer: ask ShropBot if they really are content with alpha ordering or is there an expectation for taxonomic ordering? I suspect the latter is not possible with NBN API.**

**Longer answer**

It's like in supermarkets where things are ordered in a broadly logical sequence and clustered by similarly. They're not ordered alphabetically.

Its the same with biological taxonomy.

Example: https://british-dragonflies.org.uk/species-checklist/

See how the list is not alphabetical but instead clustered by damselflies, then hawkers, emeralds, skimmers, chasers and finally darters?

Here's the key bit from the Wikipedia article (emphasis mine):

> The organization of **field guides** and taxonomic monographs may either follow or prescribe the taxonomic sequence; changes in these sequences are often introduced by new publications

So most field guides and publications use the taxon sequence to order things because it makes more sense to the readers/users of those guides. Similarly, a shopping list makes more sense if ordered by vegetables, frozen, tinned, breads, pastas, drinks, etc rather than the jumble and difficulty that would be created by ordering by alpha.

The thing is, most people that use field guides, especially as they get more expert, have internalised this order and expect it. Coupled with an alphabetic index at the back, we have two ways to browse and use the data contained therein. Books have nailed this sort of presentation and usability in a way us programmers have not. Have a scan through some field guides if you have any to see what I mean.

So when confronted with a digital tool like an online atlas for the first time, users will often start complaining about the alphabetical order, especially for long lists or lists of species found at a site. This expectation of taxon order is so ingrained, I often found that nobody asked for it until late on in the process; it was just assumed to be a certain way. Naturalists tend to assume taxon ordering, while technologists assume alpha.

And the rub is that this is a challenging problem to solve because there is no one single source of truth for all taxa. Taxonomy is a fluid conglomeration of different published lists glommed together with all sorts of versioning, splitting and lumping challenges. So the ordering usually happens at the species group level, often by the editors of the field guides. When expanding out a list of taxonomic concepts (species names and ranks etc) to everything, like the NBN and record centres do, how does an order get applied universally? It can't be easily calculated with an algorithm. It's partly (mostly?) editorial and standardisation work. Agreement between people. 

Here's a brief thread on the subject on the Recorder forum (which probably won't make much sense to you, but that doesn't matter): https://forums.nbn.org.uk/viewtopic.php?id=6544

So I don't know what the NBN Atlas does about it. Perhaps being a neutral data repository, it doesn't care? Perhaps their stance is that it is up to users how they interpret the data (which would perhaps be an example of how the NBN has not traditionally been particularly user-led)

But it's an expectation to start managing early otherwise it could lead to disappointment and disgruntled users complaining that it is useless without the ordering they expect.

The expected order can usually be found in their preferred field guide or published list of species from the BSBI or similar. E.g. see here: https://bsbi.org/taxon-lists. Download and compare the complete list (extracted from a database)  vs the short 2007 (edited) list. Note how the latter starts with the primitive stoneworts and ends with the sophisticated orchids? It's not alphabetical.

So that is all a long way of asking if they really are content to use alpha sorting or if they expect it to be more like it is in the BSBI short list. If they do need the latter, and the NBN Atlas doesn't contain this sort order, then that's a big challenge. They haven't included a sort order column in the BSBI short list, so that isn't of much help, although I would hope BSBI could shed some light.

Anyway, yes, a throny issue that needs to be confirmed and agreed on if alphabetical order is the only way to proceed in the short term. It may not be a concern for them at all because many publications do use alpha sorting such as the red list found on this page: https://bsbi.org/england (whether readers/users of that publication are satisfied with this presentation would be a good question).

You might find the following thread regarding Recorder's implementation of taxon sorting interesting: https://forums.nbn.org.uk/viewtopic.php?id=4772. See how people are dismayed at the attempted algorithmic approach producing results that are unexpected. I don't recall if this was ever properly sorted out.

Might be worth asking Chris Raper at the NHM if the UK Species Inventory has a global sort order now.

**Comment by charlesroper** [comment]
Here's a good explainer: http://www.birdwatching.com/bookstore/fieldguides_taxonomic.html

**Comment by jdrever** [comment]
Closing as not come up as an issue in feedback.
