### ISSUE TITLE
4.2.2 Map: Showing location of the site with a pin ...

### ISSUE THREAD

**Issue by jdrever** [jdrever/ShropBotSoc#62]
... since we don't have shape files for the sites, use the location of the first record.

**Comment by charlesroper** [comment]
What do think we need for this @jdrever? Needs a bit of deeper thinking.

In a typical query of records for a single species, we get back records from many sites (see attached).

Do we plot the sites over the top of the records? Thinking about it, this might be better implemented as a layer we can turn on and off so that records can be viewed would the clutter of the sites. Might not be necessary. Let's see.

Optionally, hovering over data rows could show the site pin as an enhancement (wouldn't work for touch, so would need to be an enhancement only)

- Do we plot the sites for just the visible current page? Assuming so.
- Over the top of the records?
- Need first lat/long (or OSGB GR) for each site in query results - assuming we need to wrangle the data in the model? E.g., 
    - iterate over results
    - if `[LocationId]` not already in page array add `[LocationId]` => `[latlong]` to array
    - Make page array available to controller

Does that sound about right?

![image](https://user-images.githubusercontent.com/176/115097521-bc318b00-9f22-11eb-8866-2c13c6298f5c.png)

**Comment by charlesroper** [comment]
I've got an array with site name and first latlong figured out. Going to return this with the model and then look at plotting the points in Leafleft.

**Update**: I wonder what that "Hints" entry is at the end there?

![image](https://user-images.githubusercontent.com/176/115120743-f5134380-9fa6-11eb-86c3-aab8f70559e2.png)
