### ISSUE TITLE
4.2.2 Map: Include an outline of the county and position in centre of map

### ISSUE THREAD

**Issue by jdrever** [jdrever/ShropBotSoc#66]
Use Leaflet API to position map based on Shropshire County bounds.

**Comment by jdrever** [comment]
This is already in place.

**Comment by charlesroper** [comment]
I need to work out how to get the county boundary can be centered and zoomed to in Leaflet. At the moment I think the map is  positioned using hard coded values. Because the map is different dimensions depending on screen size, it needs to be calculated.

I'll use this ticket to take that forward and will work on it soon.
